sudo: false

language: ruby

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev
      - texinfo
      - groff
      - texlive
      - texlive-fonts-recommended
      - texlive-generic-extra
      - texlive-generic-recommended
      - texlive-latex-recommended

script:
  - bundle exec middleman build
  - ./build_docs.sh
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_S3_BUCKET
  region: $AWS_S3_BUCKET_REGION
  local_dir: build
  skip_cleanup: true